package com.javatechie.aws.lambda.domain;

import java.io.Serializable;
import java.time.LocalDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.javatechie.aws.lambda.config.LocalDateTimeConverter;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "comentarios")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class Comentario implements Serializable{

	private static final long serialVersionUID = -5967632390610900346L;

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id_comentario")
    private String idComentario;
	
	@DynamoDBAttribute
	private String usuario;
	
	@DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
	private LocalDateTime fechaRegistro;
	
	/*
	 * Modulo representa , de que parte del sistema son los comentarios
	 */
	@DynamoDBAttribute
	private String identificador;
	
	@DynamoDBAttribute
	private String comentario;
	
	@DynamoDBAttribute
	private Integer puntuacion;
	
	@DynamoDBAttribute
	private boolean eliminado;
	
	@DynamoDBAttribute
	private boolean activo;
}
