package com.javatechie.aws.lambda.domain;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "compra_insight")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class CompraInsight implements Serializable {

    private static final long serialVersionUID = 173295228846668548L;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id_compra")
    private String idCompra;

    @DynamoDBAttribute(attributeName = "id_insight")
    private String idInsight;
   
    @DynamoDBAttribute
    private String telefono;

    @DynamoDBAttribute
    private String titulo;

    @DynamoDBAttribute
    private String consulta;

    @DynamoDBAttribute
    private boolean estado;

}
