package com.javatechie.aws.lambda.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@DynamoDBTable(tableName = "equipos")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class Equipo {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "id_equipo")
	private String idEquipo;
	@DynamoDBAttribute
	private String nombreEquipo;
	@DynamoDBAttribute
	private String color;
	@DynamoDBAttribute
	private Boolean estado;
}
