package com.javatechie.aws.lambda.domain;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "estado-caso")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class EstadoCaso implements Serializable  {

    private static final long serialVersionUID = -6122644555826757692L;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id_estado_caso")
    private String idEstadoCaso;
    
    @DynamoDBAttribute
    private Integer orden;
    
    @DynamoDBAttribute
    private String nombreEstado;
    
    @DynamoDBAttribute
    private boolean estado;
    
}
