package com.javatechie.aws.lambda.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@DynamoDBTable(
    tableName = "funcionarios")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class Funcionario {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  @DynamoDBAttribute(attributeName = "id_funcionario")
  private String idFuncionario;
  @DynamoDBAttribute
  private String nombres;
  @DynamoDBAttribute
  private String apellidos;
  @DynamoDBAttribute
  private Boolean estado;
}
