package com.javatechie.aws.lambda.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "infracciones")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class Infraccion {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id_infraccion")
    private String idInfraccion;

    @DynamoDBAttribute(attributeName = "base_legal")
    private String baseLegal;

    @DynamoDBAttribute(attributeName = "id_materia")
    private String idMateria;

    @DynamoDBAttribute(attributeName = "sub_materia")
    private String subMateria;

    @DynamoDBAttribute(attributeName = "descripcion")
    private String descripcion;

    @DynamoDBAttribute(attributeName = "gravedad")
    private String gravedad;

    @DynamoDBAttribute(attributeName = "prioridad")
    private Boolean prioridad;

}
