package com.javatechie.aws.lambda.domain;

import java.io.Serializable;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.javatechie.aws.lambda.domain.documents.Costo;
import com.javatechie.aws.lambda.domain.documents.PlanPrecio;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "insight")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class Insight implements Serializable {

    private static final long serialVersionUID = 7121975115894724155L;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id_insight")
    private String idInsight;

    @DynamoDBAttribute(attributeName = "nombre_caracteristica")
    private String nombreCaracteristica;

    @DynamoDBAttribute(attributeName = "label_modal")
    private String labelModal;

    @DynamoDBAttribute(attributeName = "mensaje")
    private String mensaje;

    @DynamoDBAttribute(attributeName = "caracteristicas")
    private List<String> caracteristicas;

    @DynamoDBAttribute(attributeName = "costo")
    private Costo costo;

    @DynamoDBAttribute(attributeName = "planes_precio")
    private List<PlanPrecio> planesPrecio;
    
    @DynamoDBAttribute
    private boolean estado;

}
