package com.javatechie.aws.lambda.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@DynamoDBTable(tableName = "inspectores")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class Inspector {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "id_inspector")
	private String id;
	@DynamoDBAttribute
	private String nombreInspector;
	@DynamoDBAttribute
	private String tipo;
	@DynamoDBAttribute
	private Boolean estado;
}
