package com.javatechie.aws.lambda.domain;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@DynamoDBTable(tableName = "intendencia")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class Intendencia implements Serializable {

	private static final long serialVersionUID = -3260590468362008264L;

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "id_intendencia")
	private String idIntendencia;
	
	@DynamoDBAttribute
	private String departamento;
	
	@DynamoDBAttribute
	private String instancia;
	
	@DynamoDBAttribute
	private String oficina;
	
	@DynamoDBAttribute
	private boolean estado;
	
}
