package com.javatechie.aws.lambda.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "sub_materia")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class SubMateria {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id_sub_materia")
    private String idSubMateria;

    @DynamoDBAttribute(attributeName = "nombre_sub_materia")
    private String nombreSubMateria;

    @DynamoDBAttribute(attributeName = "id_materia")
    private String idMateria;

    @DynamoDBAttribute(attributeName = "prioridad")
    private Boolean prioridad;
}
