package com.javatechie.aws.lambda.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "sub_materia")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class SubMateria {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id_sub_materia")
    @Schema(title = "Id Submateria", name = "idSubMateria", example = "026da4d7-dd05-400c-92ed-1daf7c08fc34")
    private String idSubMateria;

    @DynamoDBAttribute(attributeName = "nombre_sub_materia")
    @Schema(title = "Nombre submateria", name = "nombreSubMateria", example = "Registro")
    private String nombreSubMateria;

    @DynamoDBAttribute(attributeName = "id_materia")
    @Schema(title = "Id Materia", name = "idMateria", example = "d5dead7f-859e-446a-aea5-3d8eb86e9ca0")
    private String idMateria;

    @DynamoDBAttribute(attributeName = "prioridad")
    private Boolean prioridad;
}
