package com.javatechie.aws.lambda.domain;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "tipo_tarea")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class TipoTarea implements Serializable {

    private static final long serialVersionUID = 6034935112724664260L;
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id_tipo_tarea")
    private String idTipoTarea;
    
    @DynamoDBAttribute
    private String nombreTipo;
    
    @DynamoDBAttribute
    private boolean estado;
    
}
